/*
# Seed Initial Data - Teachers, Subjects, Staff

This migration populates the database with all department data:
- Teachers with their assignments (class, subject, form, base_hw)
- Subject curriculum (topics per form/level)
- Issue templates for department tracking

Data is sourced from the original HOD Monthly Report HTML file.
*/

-- ============================================
-- TEACHERS DATA
-- ============================================

-- Physics Teachers
INSERT INTO teachers (department_id, name, subject, class_name, form, base_hw) VALUES
('physics', 'Sebastian Nduye', 'Physics', '2A', 'F2', 4),
('physics', 'Sebastian Nduye', 'Physics', '3C', 'F3', 8),
('physics', 'Sebastian Nduye', 'Physics', '3D', 'F3', 8),
('physics', 'Sebastian Nduye', 'Physics', '6PCM', 'F6', 20),
('physics', 'Erick Sambayati', 'Physics', '6PCB1', 'F6', 20),
('physics', 'Erick Sambayati', 'Physics', '6PCB2/PMC', 'F6', 20),
('physics', 'Renatus Joseph', 'Physics', '1C', 'F1', 4),
('physics', 'Renatus Joseph', 'Physics', '1D', 'F1', 4),
('physics', 'Renatus Joseph', 'Physics', '5PCB1', 'F5', 20),
('physics', 'Renatus Joseph', 'Physics', '5PCB2', 'F5', 20),
('physics', 'Petro Athanas', 'Physics', '1A', 'F1', 4),
('physics', 'Petro Athanas', 'Physics', '1B', 'F1', 4),
('physics', 'Petro Athanas', 'Physics', '4C', 'F4', 8),
('physics', 'Petro Athanas', 'Physics', '4D', 'F4', 8),
('physics', 'Petro Athanas', 'Physics', '5PCM/PMC', 'F5', 20)
ON CONFLICT DO NOTHING;

-- Math & Tech Teachers
INSERT INTO teachers (department_id, name, subject, class_name, form, base_hw) VALUES
('math_tech', 'Aman Msanya', 'Basic Math', '2A', 'F2', 8),
('math_tech', 'Aman Msanya', 'Basic Math', '2B', 'F2', 8),
('math_tech', 'Aman Msanya', 'Basic Math', '2C', 'F2', 8),
('math_tech', 'Aman Msanya', 'Basic Math', '2D', 'F2', 8),
('math_tech', 'Daud Lubeleje', 'Basic Math', '3A', 'F3', 12),
('math_tech', 'Daud Lubeleje', 'Basic Math', '3B', 'F3', 12),
('math_tech', 'Daud Lubeleje', 'Basic Math', '3C', 'F3', 12),
('math_tech', 'Daud Lubeleje', 'Basic Math', '3D', 'F3', 12),
('math_tech', 'Goodrock Macha', 'Basic Math', '4A', 'F4', 12),
('math_tech', 'Goodrock Macha', 'Basic Math', '4B', 'F4', 12),
('math_tech', 'Goodrock Macha', 'Basic Math', '4C', 'F4', 12),
('math_tech', 'Goodrock Macha', 'Basic Math', '4D', 'F4', 12),
('math_tech', 'Joseph Tengio', 'Basic Math', '1A', 'F1', 12),
('math_tech', 'Joseph Tengio', 'Basic Math', '1B', 'F1', 12),
('math_tech', 'Joseph Tengio', 'Basic Math', '1C', 'F1', 12),
('math_tech', 'Joseph Tengio', 'Basic Math', '1D', 'F1', 12),
('math_tech', 'Jastin Bahati', 'Add Math', '3D', 'F3', 12),
('math_tech', 'Jastin Bahati', 'BAM', '5PCB1', 'F5', 12),
('math_tech', 'Jastin Bahati', 'BAM', '5PCB2', 'F5', 8),
('math_tech', 'Jastin Bahati', 'BAM', '6PCB1', 'F6', 8),
('math_tech', 'Jastin Bahati', 'BAM', '5ECA', 'F5', 20),
('math_tech', 'Jastin Bahati', 'BAM', '5CBG/CBA', 'F5', 8),
('math_tech', 'Peter Joseph', 'BAM', '6ECA', 'F6', 8),
('math_tech', 'Peter Joseph', 'BAM', '6PCB2', 'F6', 8),
('math_tech', 'Peter Joseph', 'Adv Math', '5EGM', 'F5', 20),
('math_tech', 'Kenedy Ponda', 'Add Math', '4D', 'F4', 8),
('math_tech', 'Kenedy Ponda', 'Adv Math', '6PMC', 'F6', 20),
('math_tech', 'Kenedy Ponda', 'Adv Math', '6EGM', 'F6', 20),
('math_tech', 'Mesha Twait', 'Adv Math', '6PCM', 'F6', 20),
('math_tech', 'Mesha Twait', 'Adv Math', '5PCM', 'F5', 20),
('math_tech', 'Denis Ezron', 'Computer Science', '2A', 'F2', 4),
('math_tech', 'Denis Ezron', 'Computer Science', '2B', 'F2', 4),
('math_tech', 'Piniel Materu', 'Computer Science', '2C', 'F2', 4),
('math_tech', 'Piniel Materu', 'Computer Science', '2D', 'F2', 4),
('math_tech', 'Piniel Materu', 'ICS', '4A', 'F4', 4),
('math_tech', 'Piniel Materu', 'ICS', '4B', 'F4', 4),
('math_tech', 'Piniel Materu', 'ICS', '4C', 'F4', 4),
('math_tech', 'Piniel Materu', 'ICS', '4D', 'F4', 4),
('math_tech', 'Piniel Materu', 'Computer Science', '1A', 'F1', 4),
('math_tech', 'Piniel Materu', 'Computer Science', '1B', 'F1', 4),
('math_tech', 'Piniel Materu', 'Computer Science', '1C', 'F1', 4),
('math_tech', 'Piniel Materu', 'Computer Science', '6PMC', 'F6', 4),
('math_tech', 'Edna Ngundana', 'ICS', '3A', 'F3', 4),
('math_tech', 'Edna Ngundana', 'ICS', '3B', 'F3', 4),
('math_tech', 'Edna Ngundana', 'ICS', '3C', 'F3', 4),
('math_tech', 'Edna Ngundana', 'ICS', '3D', 'F3', 4),
('math_tech', 'Edna Ngundana', 'Computer Science', '1D', 'F1', 4),
('math_tech', 'Edna Ngundana', 'Computer Science', '5PMC', 'F5', 20)
ON CONFLICT DO NOTHING;

-- Business Teachers
INSERT INTO teachers (department_id, name, subject, class_name, form, base_hw) VALUES
('business', 'Elia Materu', 'Economics', '6ECA', 'F6', 10),
('business', 'Elia Materu', 'Economics', '6EGM', 'F6', 10),
('business', 'Joseph Mwasoni', 'Commerce', '6ECA', 'F6', 10),
('business', 'Joseph Mwasoni', 'Business Studies', '5ECA', 'F5', 10),
('business', 'Joseph Mwasoni', 'Book Keeping', '1D', 'F1', 4),
('business', 'Erasto Mshima', 'Business Studies', '1A', 'F1', 4),
('business', 'Erasto Mshima', 'Business Studies', '1B', 'F1', 4),
('business', 'Erasto Mshima', 'Business Studies', '1C', 'F1', 4),
('business', 'Erasto Mshima', 'Business Studies', '1D', 'F1', 4),
('business', 'Erasto Mshima', 'Business Studies', '2A', 'F2', 4),
('business', 'Erasto Mshima', 'Business Studies', '2B', 'F2', 4),
('business', 'Erasto Mshima', 'Business Studies', '2C', 'F2', 4),
('business', 'Erasto Mshima', 'Business Studies', '2D', 'F2', 4),
('business', 'Tumaini Malaki', 'Book Keeping', '1A', 'F1', 4),
('business', 'Tumaini Malaki', 'Book Keeping', '2D', 'F2', 4),
('business', 'Tumaini Malaki', 'Book Keeping', '2C', 'F2', 4),
('business', 'Tumaini Malaki', 'Commerce', '3A', 'F3', 4),
('business', 'Tumaini Malaki', 'Commerce', '3B', 'F3', 4),
('business', 'Tumaini Malaki', 'Commerce', '4A', 'F4', 4),
('business', 'Tumaini Malaki', 'Commerce', '4B', 'F4', 4),
('business', 'Jesca Jeremia', 'Book Keeping', '1B', 'F1', 4),
('business', 'Jesca Jeremia', 'Book Keeping', '3A', 'F3', 4),
('business', 'Jesca Jeremia', 'Book Keeping', '3B', 'F3', 4),
('business', 'Jesca Jeremia', 'Book Keeping', '4A', 'F4', 4),
('business', 'Jesca Jeremia', 'Book Keeping', '4B', 'F4', 4),
('business', 'Omary Kikoba', 'Book Keeping', '1C', 'F1', 4),
('business', 'Omary Kikoba', 'Accountancy', '6ECA', 'F6', 10),
('business', 'Omary Kikoba', 'Accountancy', '5ECA', 'F5', 10),
('business', 'Anold Ayo', 'Economics', '5EGM', 'F5', 10),
('business', 'Anold Ayo', 'Economics', '5EBuAC', 'F5', 10)
ON CONFLICT DO NOTHING;

-- ABC Teachers (Biology, Chemistry, Agriculture)
INSERT INTO teachers (department_id, name, subject, class_name, form, base_hw) VALUES
('abc', 'Agnes Msando', 'Chemistry', '1A', 'F1', 6),
('abc', 'Agnes Msando', 'Chemistry', '1B', 'F1', 6),
('abc', 'Agnes Msando', 'Chemistry', '1C', 'F1', 6),
('abc', 'Agnes Msando', 'Chemistry', '1D', 'F1', 6),
('abc', 'Johari Kasselle', 'Chemistry', '2A', 'F2', 6),
('abc', 'Johari Kasselle', 'Chemistry', '2B', 'F2', 6),
('abc', 'Johari Kasselle', 'Chemistry', '6PCM', 'F6', 6),
('abc', 'Johari Kasselle', 'Chemistry', '5CBG/CBA', 'F5', 8),
('abc', 'Teddy Mashauri', 'Biology', '2B', 'F2', 6),
('abc', 'Teddy Mashauri', 'Biology', '6PCB1', 'F6', 8),
('abc', 'Teddy Mashauri', 'Biology', '6PCB2', 'F6', 8),
('abc', 'Japhet Wilson', 'Biology', '3B', 'F3', 8),
('abc', 'Japhet Wilson', 'Biology', '3D', 'F3', 8),
('abc', 'Japhet Wilson', 'Biology', '4A', 'F4', 8),
('abc', 'Japhet Wilson', 'Biology', '4B', 'F4', 8),
('abc', 'Japhet Wilson', 'Biology', '4C', 'F4', 8),
('abc', 'Japhet Wilson', 'Biology', '4D', 'F4', 8),
('abc', 'Juma Juma', 'Biology', '2A', 'F2', 6),
('abc', 'Juma Juma', 'Agriculture', '1A', 'F1', 6),
('abc', 'Juma Juma', 'Agriculture', '1B', 'F1', 6),
('abc', 'Juma Juma', 'Agriculture', '1D', 'F1', 6),
('abc', 'Juma Juma', 'Agriculture', '4C', 'F4', 6),
('abc', 'Philip Chami', 'Chemistry', '3C', 'F3', 6),
('abc', 'Philip Chami', 'Chemistry', '6PCB1', 'F6', 8),
('abc', 'Philip Chami', 'Chemistry', '6PCB2', 'F6', 8),
('abc', 'Shaban Ramadhan', 'Chemistry', '5PCB1', 'F5', 15),
('abc', 'Shaban Ramadhan', 'Chemistry', '5PCB2', 'F5', 15),
('abc', 'Shaban Shaban', 'Chemistry', '3D', 'F3', 6),
('abc', 'Shaban Shaban', 'Chemistry', '4C', 'F4', 6),
('abc', 'Shaban Shaban', 'Chemistry', '4D', 'F4', 6),
('abc', 'Shaban Shaban', 'Chemistry', '5PCM', 'F5', 6),
('abc', 'Lowassa', 'Biology', '5PCB1', 'F5', 15),
('abc', 'Hilder Mallya', 'Biology', '5PCB2', 'F5', 15),
('abc', 'Hilder Mallya', 'Biology', '3A', 'F3', 6),
('abc', 'Hilder Mallya', 'Biology', '5CBG/CBA', 'F5', 6),
('abc', 'Ibrahim Danford', 'Agriculture', '6PCB2', 'F6', 6),
('abc', 'Ibrahim Danford', 'Agriculture', '5CBA', 'F5', 6),
('abc', 'Humphrey Nkya', 'Biology', '1A', 'F1', 6),
('abc', 'Humphrey Nkya', 'Biology', '1B', 'F1', 6),
('abc', 'Revocatus Leopod', 'Biology', '2A', 'F2', 6),
('abc', 'Revocatus Leopod', 'Biology', '1D', 'F1', 6),
('abc', 'Revocatus Leopod', 'Biology', '3C', 'F3', 6),
('abc', 'Revocatus Leopod', 'Agriculture', '1A', 'F1', 6)
ON CONFLICT DO NOTHING;

-- Humanities Teachers (History, Geography)
INSERT INTO teachers (department_id, name, subject, class_name, form, base_hw) VALUES
('humanities', 'Emma Amid', 'History', '1A', 'F1', 3),
('humanities', 'Emma Amid', 'History', '1B', 'F1', 3),
('humanities', 'Emma Amid', 'History', '1C', 'F1', 2),
('humanities', 'Emma Amid', 'History', '1D', 'F1', 2),
('humanities', 'Emma Amid', 'History', '3A', 'F3', 4),
('humanities', 'Emma Amid', 'History', '3B', 'F3', 4),
('humanities', 'Emma Amid', 'History', '3C', 'F3', 4),
('humanities', 'Emma Amid', 'History', '3D', 'F3', 4),
('humanities', 'Emma Amid', 'History', '4A', 'F4', 4),
('humanities', 'Emma Amid', 'History', '4D', 'F4', 4),
('humanities', 'Rosemary Shayo', 'History', '2C', 'F2', 2),
('humanities', 'Rosemary Shayo', 'History', '2D', 'F2', 2),
('humanities', 'Rosemary Shayo', 'History', '4B', 'F4', 4),
('humanities', 'Rosemary Shayo', 'History', '4C', 'F4', 4),
('humanities', 'Ezra Zablon', 'History', '6HGL', 'F6', 10),
('humanities', 'Ezra Zablon', 'History', '6HGK', 'F6', 10),
('humanities', 'Joseph Dasare', 'History', '5HGL', 'F5', 10),
('humanities', 'Joseph Dasare', 'History', '5HGK', 'F5', 10),
('humanities', 'Tsingay', 'Geography', '1B', 'F1', 4),
('humanities', 'Stephen Andrew', 'Geography', '1A', 'F1', 4),
('humanities', 'Stephen Andrew', 'Geography', '5EGM', 'F5', 10),
('humanities', 'Goodluck Swai', 'Geography', '2C', 'F2', 4),
('humanities', 'Goodluck Swai', 'Geography', '2D', 'F2', 4),
('humanities', 'Goodluck Swai', 'Geography', '5HGL', 'F5', 10),
('humanities', 'Goodluck Swai', 'Geography', '5HGK', 'F5', 10),
('humanities', 'Frank Kachema', 'Geography', '2A', 'F2', 4),
('humanities', 'Frank Kachema', 'Geography', '2B', 'F2', 4),
('humanities', 'Frank Kachema', 'Geography', '6EGM', 'F6', 10),
('humanities', 'Mkama Pamba', 'Geography', '1C', 'F1', 4),
('humanities', 'Mkama Pamba', 'Geography', '1D', 'F1', 4),
('humanities', 'Mkama Pamba', 'Geography', '6HGK', 'F6', 10),
('humanities', 'Mkama Pamba', 'Geography', '6HGL', 'F6', 10),
('humanities', 'Eunice Ndekirwa', 'Geography', '3A', 'F3', 4),
('humanities', 'Eunice Ndekirwa', 'Geography', '3B', 'F3', 4),
('humanities', 'Eunice Ndekirwa', 'Geography', '3C', 'F3', 4),
('humanities', 'Eunice Ndekirwa', 'Geography', '3D', 'F3', 4),
('humanities', 'Eunice Ndekirwa', 'Geography', '4A', 'F4', 4),
('humanities', 'Eunice Ndekirwa', 'Geography', '4B', 'F4', 4),
('humanities', 'Eunice Ndekirwa', 'Geography', '4C', 'F4', 4),
('humanities', 'Eunice Ndekirwa', 'Geography', '4D', 'F4', 4),
('humanities', 'Salome Yamba', 'Geography', '5CBG', 'F5', 2)
ON CONFLICT DO NOTHING;

-- Languages Teachers (English, Kiswahili, Literature)
INSERT INTO teachers (department_id, name, subject, class_name, form, base_hw) VALUES
('languages', 'Samwel Saji', 'English', '1A', 'F1', 4),
('languages', 'Samwel Saji', 'English', '1B', 'F1', 4),
('languages', 'Samwel Saji', 'Literature', '3A', 'F3', 4),
('languages', 'Samwel Saji', 'Literature', '3B', 'F3', 4),
('languages', 'Samwel Saji', 'Literature', '4A', 'F4', 2),
('languages', 'Samwel Saji', 'Academic Communication', '5PMC/PCM', 'F5', 2),
('languages', 'Samwel Saji', 'Academic Communication', '5CBG/CBA', 'F5', 2),
('languages', 'Samwel Saji', 'Academic Communication', '5EGM', 'F5', 2),
('languages', 'Anna Tataya', 'English', '1C', 'F1', 4),
('languages', 'Anna Tataya', 'English', '1D', 'F1', 4),
('languages', 'Anna Tataya', 'English', '3A', 'F3', 4),
('languages', 'Anna Tataya', 'English', '3B', 'F3', 4),
('languages', 'Anna Tataya', 'English', '3C', 'F3', 4),
('languages', 'Anna Tataya', 'Academic Communication', '5HGL', 'F5', 4),
('languages', 'Anna Tataya', 'Academic Communication', '5PCB1', 'F5', 2),
('languages', 'Cleopa Joseph', 'English', '4A', 'F4', 4),
('languages', 'Cleopa Joseph', 'English', '4B', 'F4', 4),
('languages', 'Cleopa Joseph', 'English', '4C', 'F4', 4),
('languages', 'Cleopa Joseph', 'English', '4D', 'F4', 4),
('languages', 'Cleopa Joseph', 'English', '6HGL', 'F6', 10),
('languages', 'Samwel James', 'English', '2A', 'F2', 4),
('languages', 'Samwel James', 'English', '2B', 'F2', 4),
('languages', 'Samwel James', 'English', '2C', 'F2', 4),
('languages', 'Samwel James', 'English', '2D', 'F2', 4),
('languages', 'Samwel James', 'English', '3D', 'F3', 4),
('languages', 'Samwel James', 'Academic Communication', '5EBUAC', 'F5', 2),
('languages', 'Samwel James', 'Kiswahili', '1B', 'F1', 4),
('languages', 'Joseph Mollel', 'English', '5HGL', 'F5', 10),
('languages', 'Joseph Mollel', 'English', '5HGL/HGK', 'F5', 10),
('languages', 'Clement Sarakikya', 'Kiswahili', '1A', 'F1', 4),
('languages', 'Clement Sarakikya', 'Kiswahili', '4A', 'F4', 4),
('languages', 'Clement Sarakikya', 'Kiswahili', '4B', 'F4', 4),
('languages', 'Clement Sarakikya', 'Kiswahili', '4C', 'F4', 4),
('languages', 'Clement Sarakikya', 'Kiswahili', '4D', 'F4', 4),
('languages', 'Clement Sarakikya', 'Kiswahili', '6HGK', 'F6', 10),
('languages', 'Emma Edward', 'Kiswahili', '1C', 'F1', 4),
('languages', 'Emma Edward', 'Kiswahili', '3A', 'F3', 4),
('languages', 'Emma Edward', 'Kiswahili', '3B', 'F3', 4),
('languages', 'Emma Edward', 'Kiswahili', '3C', 'F3', 4),
('languages', 'Emma Edward', 'Kiswahili', '3D', 'F3', 4),
('languages', 'Emma Edward', 'Kiswahili', '5HGK', 'F5', 10),
('languages', 'Rosemary Shayo', 'Kiswahili', '1D', 'F1', 4),
('languages', 'Rosemary Shayo', 'Kiswahili', '2A', 'F2', 4),
('languages', 'Rosemary Shayo', 'Kiswahili', '2B', 'F2', 4),
('languages', 'Rosemary Shayo', 'Kiswahili', '2C', 'F2', 4),
('languages', 'Rosemary Shayo', 'Kiswahili', '2D', 'F2', 4),
('languages', 'Ezra Zablon', 'Academic Communication', '5HGK', 'F5', 3),
('languages', 'Ezra Zablon', 'Academic Communication', '5PCB2', 'F5', 3)
ON CONFLICT DO NOTHING;

-- Vocational Teachers (Bible Knowledge, Fine Art, Music, HTM, Civics, General Studies)
INSERT INTO teachers (department_id, name, subject, class_name, form, base_hw) VALUES
('vocational', 'Firmin Kiwale', 'Bible Knowledge', '1A', 'F1', 3),
('vocational', 'Firmin Kiwale', 'Bible Knowledge', '1B', 'F1', 3),
('vocational', 'Firmin Kiwale', 'Bible Knowledge', '1C', 'F1', 3),
('vocational', 'Firmin Kiwale', 'Bible Knowledge', '1D', 'F1', 3),
('vocational', 'Firmin Kiwale', 'Bible Knowledge', '2C', 'F2', 3),
('vocational', 'Firmin Kiwale', 'Bible Knowledge', '2D', 'F2', 3),
('vocational', 'Firmin Kiwale', 'Bible Knowledge', '3A', 'F3', 3),
('vocational', 'Firmin Kiwale', 'Bible Knowledge', '3B', 'F3', 3),
('vocational', 'Deogratias Nunda', 'Bible Knowledge', '3C', 'F3', 3),
('vocational', 'Deogratias Nunda', 'Bible Knowledge', '3D', 'F3', 3),
('vocational', 'Deogratias Nunda', 'Bible Knowledge', '4A', 'F4', 3),
('vocational', 'Deogratias Nunda', 'Bible Knowledge', '4B', 'F4', 3),
('vocational', 'Deogratias Nunda', 'Bible Knowledge', '4C', 'F4', 3),
('vocational', 'Deogratias Nunda', 'Bible Knowledge', '4D', 'F4', 3),
('vocational', 'Deogratias Nunda', 'General Studies', '6PCM', 'F6', 3),
('vocational', 'Deogratias Nunda', 'General Studies', '6PCB1', 'F6', 3),
('vocational', 'Deogratias Nunda', 'General Studies', '6PCB2', 'F6', 3),
('vocational', 'Deogratias Nunda', 'General Studies', '6HGL', 'F6', 3),
('vocational', 'Deogratias Nunda', 'General Studies', '6HGK', 'F6', 3),
('vocational', 'Uswege Emmanuel', 'Fine Art', '1A', 'F1', 3),
('vocational', 'Uswege Emmanuel', 'Fine Art', '1B', 'F1', 3),
('vocational', 'Uswege Emmanuel', 'Fine Art', '1C', 'F1', 3),
('vocational', 'Uswege Emmanuel', 'Fine Art', '1D', 'F1', 3),
('vocational', 'Uswege Emmanuel', 'Fine Art', '2A', 'F2', 3),
('vocational', 'Uswege Emmanuel', 'Fine Art', '2B', 'F2', 3),
('vocational', 'Uswege Emmanuel', 'Fine Art', '2C', 'F2', 3),
('vocational', 'Uswege Emmanuel', 'Fine Art', '2D', 'F2', 3),
('vocational', 'Uswege Emmanuel', 'Fine Art', '3A', 'F3', 3),
('vocational', 'Uswege Emmanuel', 'Fine Art', '3B', 'F3', 3),
('vocational', 'Uswege Emmanuel', 'Fine Art', '3C', 'F3', 3),
('vocational', 'Uswege Emmanuel', 'Fine Art', '3D', 'F3', 3),
('vocational', 'Uswege Emmanuel', 'Fine Art', '4A', 'F4', 3),
('vocational', 'Uswege Emmanuel', 'Fine Art', '4B', 'F4', 3),
('vocational', 'Uswege Emmanuel', 'Fine Art', '4C', 'F4', 3),
('vocational', 'Uswege Emmanuel', 'Fine Art', '4D', 'F4', 3),
('vocational', 'Maria Kaozya', 'Music', '1A', 'F1', 3),
('vocational', 'Maria Kaozya', 'Music', '1B', 'F1', 3),
('vocational', 'Maria Kaozya', 'Music', '1C', 'F1', 3),
('vocational', 'Maria Kaozya', 'Music', '1D', 'F1', 3),
('vocational', 'Maria Kaozya', 'Music', '2A', 'F2', 3),
('vocational', 'Maria Kaozya', 'Music', '2B', 'F2', 3),
('vocational', 'Maria Kaozya', 'Music', '2C', 'F2', 3),
('vocational', 'Maria Kaozya', 'Music', '2D', 'F2', 3),
('vocational', 'Maria Kaozya', 'Music', '3A', 'F3', 3),
('vocational', 'Maria Kaozya', 'Music', '3B', 'F3', 3),
('vocational', 'Maria Kaozya', 'Music', '3C', 'F3', 3),
('vocational', 'Maria Kaozya', 'Music', '3D', 'F3', 3),
('vocational', 'Maria Kaozya', 'Music', '4A', 'F4', 3),
('vocational', 'Maria Kaozya', 'Music', '4B', 'F4', 3),
('vocational', 'Maria Kaozya', 'Music', '4C', 'F4', 3),
('vocational', 'Maria Kaozya', 'Music', '4D', 'F4', 3),
('vocational', 'Wema Ollo', 'HTM', '2A', 'F2', 2),
('vocational', 'Wema Ollo', 'HTM', '2B', 'F2', 2),
('vocational', 'Wema Ollo', 'HTM', '2C', 'F2', 2),
('vocational', 'Wema Ollo', 'HTM', '2D', 'F2', 2),
('vocational', 'Wema Ollo', 'Civics', '3A', 'F3', 2),
('vocational', 'Wema Ollo', 'Civics', '3B', 'F3', 2),
('vocational', 'Wema Ollo', 'Civics', '3C', 'F3', 2),
('vocational', 'Wema Ollo', 'Civics', '3D', 'F3', 2),
('vocational', 'Wema Ollo', 'Civics', '4A', 'F4', 2),
('vocational', 'Wema Ollo', 'Civics', '4B', 'F4', 2),
('vocational', 'Wema Ollo', 'Civics', '4C', 'F4', 2),
('vocational', 'Wema Ollo', 'Civics', '4D', 'F4', 2),
('vocational', 'Frank Kachema', 'HTM', '1A', 'F1', 3),
('vocational', 'Frank Kachema', 'HTM', '1B', 'F1', 3),
('vocational', 'Frank Kachema', 'HTM', '1C', 'F1', 3),
('vocational', 'Frank Kachema', 'HTM', '1D', 'F1', 3),
('vocational', 'Gift Mollel', 'HTM', '5HGL', 'F5', 4),
('vocational', 'Gift Mollel', 'HTM', '5EGM', 'F5', 4),
('vocational', 'Gift Mollel', 'HTM', '5ECA', 'F5', 4),
('vocational', 'Gift Mollel', 'HTM', '5CBG/CBA', 'F5', 4),
('vocational', 'Gift Mollel', 'General Studies', '6EGM', 'F6', 2),
('vocational', 'Gift Mollel', 'General Studies', '6ECA', 'F6', 2),
('vocational', 'Gift Mollel', 'General Studies', '6PMCs', 'F6', 2),
('vocational', 'Salome Yamba', 'HTM', '5HGL', 'F5', 4),
('vocational', 'Salome Yamba', 'HTM', '5PMC/PCM', 'F5', 4),
('vocational', 'Salome Yamba', 'HTM', '5PCB2', 'F5', 4),
('vocational', 'Salome Yamba', 'HTM', '5PCB1', 'F5', 4)
ON CONFLICT DO NOTHING;

-- ============================================
-- SUBJECTS DATA
-- ============================================

-- Physics Subjects
INSERT INTO subjects (department_id, subject_name, form, level, topics) VALUES
('physics', 'Physics', 'F1', 'O-Level', 7),
('physics', 'Physics', 'F2', 'O-Level', 6),
('physics', 'Physics', 'F3', 'O-Level', 9),
('physics', 'Physics', 'F4', 'O-Level', 7),
('physics', 'Physics', 'F5', 'A-Level', 5),
('physics', 'Physics', 'F6', 'A-Level', 5)
ON CONFLICT (department_id, subject_name, form) DO NOTHING;

-- ABC Subjects
INSERT INTO subjects (department_id, subject_name, form, level, topics) VALUES
('abc', 'Biology', 'F1', 'O-Level', 4),
('abc', 'Biology', 'F2', 'O-Level', 2),
('abc', 'Biology', 'F3', 'O-Level', 5),
('abc', 'Biology', 'F4', 'O-Level', 5),
('abc', 'Biology', 'F5', 'A-Level', 4),
('abc', 'Biology', 'F6', 'A-Level', 6),
('abc', 'Chemistry', 'F1', 'O-Level', 2),
('abc', 'Chemistry', 'F2', 'O-Level', 2),
('abc', 'Chemistry', 'F3', 'O-Level', 9),
('abc', 'Chemistry', 'F4', 'O-Level', 5),
('abc', 'Chemistry', 'F5', 'A-Level', 6),
('abc', 'Chemistry', 'F6', 'A-Level', 5),
('abc', 'Agriculture', 'F1', 'O-Level', 3),
('abc', 'Agriculture', 'F2', 'O-Level', 7),
('abc', 'Agriculture', 'F3', 'O-Level', 5),
('abc', 'Agriculture', 'F4', 'O-Level', 5),
('abc', 'Agriculture', 'F5', 'A-Level', 9),
('abc', 'Agriculture', 'F6', 'A-Level', 6)
ON CONFLICT (department_id, subject_name, form) DO NOTHING;

-- Math & Tech Subjects
INSERT INTO subjects (department_id, subject_name, form, level, topics) VALUES
('math_tech', 'Mathematics', 'F1', 'O-Level', 5),
('math_tech', 'Mathematics', 'F2', 'O-Level', 5),
('math_tech', 'Basic Mathematics', 'F3', 'O-Level', 8),
('math_tech', 'Basic Mathematics', 'F4', 'O-Level', 8),
('math_tech', 'Additional Mathematics', 'F3', 'O-Level', 6),
('math_tech', 'Additional Mathematics', 'F4', 'O-Level', 7),
('math_tech', 'ADV. Mathematics', 'F5', 'A-Level', 10),
('math_tech', 'ADV. Mathematics', 'F6', 'A-Level', 8),
('math_tech', 'BAM', 'F5', 'A-Level', 6),
('math_tech', 'BAM', 'F6', 'A-Level', 5),
('math_tech', 'Computer Science', 'F1', 'O-Level', 4),
('math_tech', 'Computer Science', 'F2', 'O-Level', 2),
('math_tech', 'ICS', 'F3', 'O-Level', 3),
('math_tech', 'ICS', 'F4', 'O-Level', 4),
('math_tech', 'Computer Science', 'F5', 'A-Level', 8),
('math_tech', 'Computer Science', 'F6', 'A-Level', 6)
ON CONFLICT (department_id, subject_name, form) DO NOTHING;

-- Business Subjects
INSERT INTO subjects (department_id, subject_name, form, level, topics) VALUES
('business', 'Business Studies', 'F1', 'O-Level', 1),
('business', 'Business Studies', 'F2', 'O-Level', 3),
('business', 'Business Studies', 'F5', 'A-Level', 11),
('business', 'Commerce', 'F3', 'O-Level', 5),
('business', 'Commerce', 'F4', 'O-Level', 5),
('business', 'Commerce', 'F6', 'A-Level', 11),
('business', 'Book Keeping', 'F1', 'O-Level', 5),
('business', 'Book Keeping', 'F2', 'O-Level', 3),
('business', 'Book Keeping', 'F3', 'O-Level', 4),
('business', 'Book Keeping', 'F4', 'O-Level', 5),
('business', 'Economics', 'F5', 'A-Level', 3),
('business', 'Economics', 'F6', 'A-Level', 9),
('business', 'Accountancy', 'F5', 'A-Level', 4),
('business', 'Accountancy', 'F6', 'A-Level', 10)
ON CONFLICT (department_id, subject_name, form) DO NOTHING;

-- Humanities Subjects
INSERT INTO subjects (department_id, subject_name, form, level, topics) VALUES
('humanities', 'History', 'F1', 'O-Level', 3),
('humanities', 'History', 'F2', 'O-Level', 2),
('humanities', 'History', 'F3', 'O-Level', 4),
('humanities', 'History', 'F4', 'O-Level', 4),
('humanities', 'History', 'F5', 'A-Level', 7),
('humanities', 'History', 'F6', 'A-Level', 8),
('humanities', 'Geography', 'F1', 'O-Level', 2),
('humanities', 'Geography', 'F2', 'O-Level', 2),
('humanities', 'Geography', 'F3', 'O-Level', 7),
('humanities', 'Geography', 'F4', 'O-Level', 5),
('humanities', 'Geography', 'F5', 'A-Level', 7),
('humanities', 'Geography', 'F6', 'A-Level', 5)
ON CONFLICT (department_id, subject_name, form) DO NOTHING;

-- Languages Subjects
INSERT INTO subjects (department_id, subject_name, form, level, topics) VALUES
('languages', 'English', 'F1', 'O-Level', 10),
('languages', 'English', 'F2', 'O-Level', 9),
('languages', 'English', 'F3', 'O-Level', 6),
('languages', 'English', 'F4', 'O-Level', 6),
('languages', 'Kiswahili', 'F1', 'O-Level', 7),
('languages', 'Kiswahili', 'F2', 'O-Level', 5),
('languages', 'Kiswahili', 'F3', 'O-Level', 7),
('languages', 'Kiswahili', 'F4', 'O-Level', 6),
('languages', 'Kiswahili', 'F5', 'A-Level', 9),
('languages', 'Kiswahili', 'F6', 'A-Level', 5),
('languages', 'Literature', 'F3', 'O-Level', 4),
('languages', 'Literature', 'F4', 'O-Level', 2),
('languages', 'Academic Communication', 'F5', 'A-Level', 7)
ON CONFLICT (department_id, subject_name, form) DO NOTHING;

-- Vocational Subjects
INSERT INTO subjects (department_id, subject_name, form, level, topics) VALUES
('vocational', 'Bible Knowledge', 'F1', 'O-Level', 2),
('vocational', 'Bible Knowledge', 'F2', 'O-Level', 5),
('vocational', 'Bible Knowledge', 'F3', 'O-Level', 10),
('vocational', 'Bible Knowledge', 'F4', 'O-Level', 5),
('vocational', 'HTM', 'F1', 'O-Level', 7),
('vocational', 'HTM', 'F2', 'O-Level', 4),
('vocational', 'HTM', 'F5', 'A-Level', 3),
('vocational', 'Civics', 'F3', 'O-Level', 6),
('vocational', 'Civics', 'F4', 'O-Level', 2),
('vocational', 'Fine Art', 'F1', 'O-Level', 3),
('vocational', 'Fine Art', 'F2', 'O-Level', 2),
('vocational', 'Fine Art', 'F3', 'O-Level', 2),
('vocational', 'Fine Art', 'F4', 'O-Level', 2),
('vocational', 'Music', 'F1', 'O-Level', 4),
('vocational', 'Music', 'F2', 'O-Level', 4),
('vocational', 'Music', 'F3', 'O-Level', 4),
('vocational', 'Music', 'F4', 'O-Level', 4),
('vocational', 'Physical Education', 'F1', 'O-Level', 10),
('vocational', 'Physical Education', 'F2', 'O-Level', 7),
('vocational', 'Physical Education', 'F3', 'O-Level', 6),
('vocational', 'Physical Education', 'F4', 'O-Level', 6),
('vocational', 'General Studies', 'F5', 'A-Level', 4),
('vocational', 'General Studies', 'F6', 'A-Level', 3)
ON CONFLICT (department_id, subject_name, form) DO NOTHING;
